### ISSUE TITLE
fix: Gulp sass-lint 

### ISSUE THREAD

**Issue by maxime1992** [maxime1992/web-template#11]
https://github.com/sasstools/sass-lint/issues/389

Not sure we can solve this by ourselves but propose something for Windows users

![error](https://cloud.githubusercontent.com/assets/4950209/13076701/6fe8ba7c-d4b4-11e5-80bf-0880dbd3b035.png)

**Comment by ghpabs** [comment]
I think it's to do with EOL being CRLF in Windows - try converting it to LF.

**Comment by kevincaradant** [comment]
done :)

Look this : https://github.com/kevincaradant/web-template/commit/43cf2e98fd325d137488d4b1e0b67e16ed5a614e

We can't put a carriage return at the end of the scss file with windows ... otherwise the plugin crash
