### ISSUE TITLE
feat: Zip the build project including version number and timestamp

### ISSUE THREAD

**Issue by maxime1992** [maxime1992/web-template#18]
Something like :
[project-name]-[version-number]-[timestamp].zip

Where `project-name` & `version-number` comes from package.json.

**Comment by maxime1992** [comment]
I think `gulp zip` could be cool.
If folder `build` is not here, warn the user and exit otherwise use it.

**Comment by Aeryax** [comment]
Hi,

I think `[project-name]-[project-version]-[yyyyMMdd]-[hhmmss].zip` is better. It's easier to know when it was built.

**Comment by maxime1992** [comment]
Cool for me, I let you do that :)
