### ISSUE TITLE
fix: Use gulp-rimraf instead of gulp-clean and gulp-cssnano instead of gulp-minimy-css

### ISSUE THREAD

**Issue by kevincaradant** [maxime1992/web-template#22]

**Comment by maxime1992** [comment]
@Aeryax maybe you could also do that in your PR : https://github.com/maxime1992/web-template/pull/20

**Comment by kevincaradant** [comment]
In fact, gulp-clean must have to be delete ;). No need to replace it with gulp-rimraf
